### ISSUE TITLE
Technical: DNS:  $3BotDoubleName.grid.tf goes to the right 3bot which terminates the ssl

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/info_3bot#24]
https://github.com/threefoldfoundation/3bot/blob/master/specs/urls.md
- [x] [collect IPs for the 3bots from blockchain](https://github.com/threefoldfoundation/3bot/issues/12)
  - [x] implement coredns plugin to read 3bot record from explorers
- [ ] template to deploy the proposed infrastructure
   - [X] coredns infrastructure that serves 3bot dns entries (utilizes cordns templates) (https://github.com/threefoldtech/0-templates/commit/00aecf2377fff8caa7da019d3858b718e86545ad)
   - [ ] traefik per location (utilize traefik template)
- [ ] ssl certificate  by let's encrypt in the 3bot website (that's application responsibility to generate certificates using let's encrypt)

![3bot_DNS](https://user-images.githubusercontent.com/303164/56811529-33068280-6839-11e9-8445-3bb75e7acae4.png)

- HA of the 3bots isn't a concern
- Traefik configurations are coming from  etcd
- CoreDNS configurations are coming blockchain

**Comment by xmonader** [comment]
I tried to use traefik as tcp with multiple applications that use letsencrypt and docs are bit shallow. it worked with the least hassle with haproxy

```
global
  log /dev/log    local0
  log /dev/log    local1 notice
  stats socket /haproxy-admin.sock mode 660 level admin
  stats timeout 30s
  daemon
defaults
  maxconn 1000
  mode http 
  log global
  timeout connect 5000
  timeout client 2000000 # ddos protection
  timeout server 2000000 # stick-table type ip size 100k expire 30s store conn_cur

frontend ft_server1
        bind 0.0.0.0:443
        mode tcp
        option tcplog
        tcp-request inspect-delay 10s
        tcp-request content accept if { req_ssl_hello_type 1 }
        use_backend bk_server1 if { req.ssl_sni -m end first.mybot.testbots.grid.tf }
        use_backend bk_server2 if { req.ssl_sni -m end second.mybot.testbots.grid.tf }
backend bk_server1
        mode tcp
        option ssl-hello-chk
        server srv1 172.18.0.35:443

backend bk_server2
        mode tcp
        option ssl-hello-chk
        server srv1 172.18.0.44:443
```

but I can imagine we need loading backends and frontends must be dynamic via etcd or something. 

While using haproxy I spotted a problem in the coredns regarding CAA records fixed here 
https://github.com/threefoldtech/threebot_coredns/pull/3/files

**Comment by xmonader** [comment]
I added bug for traefik here https://github.com/containous/traefik/issues/4906

```toml


[global]
  debug = true
  logLevel = "DEBUG"
[entryPoints]
  [entryPoints.tcp]
  address = "0.0.0.0:443"

[api]

[providers.file]




[tcp]
[tcp.services]
    [tcp.services.caddy1.LoadBalancer]
      [[tcp.services.caddy1.LoadBalancer.servers]]
        address = "172.18.0.35:443"
    [tcp.services.caddy2.LoadBalancer]
      [[tcp.services.caddy2.LoadBalancer.servers]]
        address = "172.18.0.44:443"



[tcp.routers]
    [tcp.routers.caddy1]
      entrypoints = ["tcp"]
      rule = "HostSNI(`first.mybot.testbots.grid.tf`)"
      service = "caddy1"
    [tcp.routers.caddy1.tls]
       passthrough=true


    [tcp.routers.caddy2]
      entrypoints = ["tcp"]
      rule = "HostSNI(`second.mybot.testbots.grid.tf`)"
      service = "caddy2"
    [tcp.routers.caddy2.tls]
       passthrough=true
```

Sometimes it works and lets the applications (caddy servers) generate certificates  and sometimes it shows this suspicious output `first certificate had names "2994d0b30ee2a6c063d0807f04c5da8e.e5f74b8b9ea9099ff69e5191f302b630.traefik.default, traefik default`
